$engine: 3
$onesync: on
name: RedM Server Boilerplate
description: RedM Server Boilerplate by Spooni (VORP)
author: Spooni

tasks:
  # Download Base Files
  - action: download_github
    src: https://github.com/Emotion06/myBoilerplate
    ref: main
    dest: ./temp/redm-server-boilerplate

  # Move the CFG Files
  - action: move_path
    src: ./temp/redm-server-boilerplate/cfg/server.cfg
    dest: ./server.cfg
  - action: move_path
    src: ./temp/redm-server-boilerplate/cfg/perms.cfg
    dest: ./perms.cfg
  - action: move_path
    src: ./temp/redm-server-boilerplate/cfg/resources.cfg
    dest: ./resources.cfg

  # Move the Server Icon
  - action: move_path
    src: ./temp/redm-server-boilerplate/icon.png
    dest: ./icon.png

  # Download CFX Server Data
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx]

  # Download Essentials
  - action: download_file
    path: ./tmp/files/oxmysql.zip
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
  - action: unzip
    dest: ./resources/[essentials]
    src: ./tmp/files/oxmysql.zip
    
  - action: download_file
    path: ./tmp/files/ox_lib.zip
    url: https://github.com/overextended/ox_lib/releases/latest/download/ox_lib.zip
  - action: unzip
    dest: ./resources/[essentials]
    src: ./tmp/files/ox_lib.zip

  - action: download_github
    dest: ./resources/[essentials]/weathersync
    ref: main
    src: https://github.com/Hailey-Ross/weathersync

  - action: download_github
    dest: ./resources/[essentials]/interiors
    ref: main
    src: https://github.com/Hailey-Ross/psn_interiors

  - action: download_github
    dest: ./resources/[essentials]/uiprompt
    ref: master
    src: https://github.com/kibook/redm-uiprompt

  - action: download_github
    dest: ./resources/[essentials]/jo_libs
    ref: main
    src: https://github.com/Jump-On-Studios/RedM-jo_libs

  # Download Framework

  - action: download_github
    src: https://github.com/VORPCORE/vorp_core-lua
    ref: main
    dest: ./resources/[vorp]/vorp_core

  - action: download_github
    src: https://github.com/VORPCORE/vorp_inventory-lua
    ref: main
    dest: ./resources/[vorp]/vorp_inventory

  - action: download_github
    src: https://github.com/VORPCORE/vorp_character-lua
    ref: main
    dest: ./resources/[vorp]/vorp_character 

  - action: download_github
    src: https://github.com/VORPCORE/vorp_inputs-lua
    ref: main
    dest: ./resources/[vorp]/vorp_inputs

  - action: download_github
    src: https://github.com/VORPCORE/vorp_utils
    ref: main
    dest: ./resources/[vorp]/vorp_utils

  - action: download_github
    src: https://github.com/VORPCORE/vorp_traffic
    ref: main
    dest: ./resources/[vorp]/vorp_traffic
    
  - action: download_github
    src: https://github.com/VORPCORE/vorp_radius
    ref: main
    dest: ./resources/[vorp]/vorp_radius
    
  - action: download_github
    src: https://github.com/VORPCORE/vorp_progressbar
    ref: main
    dest: ./resources/[vorp]/vorp_progressbar

  - action: download_github
    dest: ./resources/[vorp]/vorp_menu
    ref: main
    src: https://github.com/VORPCORE/vorp_menu

  - action: download_github
    dest: ./resources/[vorp]/vorp_admin
    ref: main
    src: https://github.com/VORPCORE/vorp_admin

  # Download Framework Addons
  - action: download_github
    dest: ./resources/[vorp]/vorp_zonenotify
    ref: main
    src: https://github.com/VORPCORE/vorp_zonenotify

  - action: download_github
    dest: ./resources/[vorp]/vorp_imapviewtool
    ref: main
    src: https://github.com/VORPCORE/vorp_imapviewtool

  - action: download_github
    dest: ./resources/[vorp]/vorp_barbershop
    ref: main
    src: https://github.com/VORPCORE/vorp_barbershop_lua

  - action: download_github
    dest: ./resources/[vorp]/vorp_fishing
    ref: main
    src: https://github.com/VORPCORE/vorp_fishing-lua

  - action: download_github
    dest: ./resources/[vorp]/vorp_banking
    ref: main
    src: https://github.com/VORPCORE/vorp_banking

  # Downlad Spooni 
  - action: download_github
    dest: ./resources/[spooni]/spooni_interactions
    ref: main
    src: https://github.com/Spooni-Development/spooni_interactions

  - action: download_github
    dest: ./resources/[spooni]/spooni_jobblips
    ref: main
    src: https://github.com/Spooni-Development/spooni_jobblips

  - action: download_github
    dest: ./resources/[spooni]/spooni_spooner
    ref: main
    src: https://github.com/Spooni-Development/spooni_spooner

  # Clean up db files
  - action: remove_path
    path: ./resources/[cfx]/[gamemodes]/[maps]/fivem-map-hipster

  - action: remove_path
    path: ./resources/[cfx]/[gamemodes]/[maps]/fivem-map-skater

  - action: remove_path
    path: ./temp